apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
  labels:
    app: yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: frontend
          image: ondiekifrank/clientapp:1.0
          ports:
            - containerPort: 80
        - name: backend
          image: ondiekifrank/backend:1.01
          ports:
            - containerPort: 3000
        - name: database
          image: ondiekifrank/mongodb:1.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
