version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map port 3000 in the container to port 3001 on the host
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27017"  # Map port 27017 in the container to port 27018 on the host
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
