version: '3.9'

services:
  backend:
    image: ondiekifrank/backend:1.01
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/yolomy

  frontend:
    image: ondiekifrank/clientapp:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: ondiekifrank/mongodb:1.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
