version: '3.8'

services:
  backend:
    image: ondiekifrank/backend:1.01
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - yolo-network

  frontend:
    image: ondiekifrank/clientapp:v1.0
    ports:
      - "80:80"
    depends_on:
      - mongodb
    networks:
      - yolo-network

  mongodb:
    image: ondiekifrank/mongodb:1.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

volumes:
  mongo-data:
