apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-0
spec:
  containers:
  - name: mongodb
    image: mongo
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - mountPath: /data/db
      name: mongodb-data
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-persistent-storage
