---
- name: Deploy e-commerce application
  hosts: all
  become: yes
  tasks:
    - name: Install Node.js (frontend)
      apt:
        name: nodejs
        state: present
      tags: frontend

    - name: Install npm (frontend)
      apt:
        name: npm
        state: present
      tags: frontend

    - name: Remove existing frontend directory
      file:
        path: /var/www/frontend
        state: absent
      tags: frontend

    - name: Clone frontend repository (full clone)
      git:
        repo: 'https://github.com/OndiekiFrank/yolo.git'
        dest: /var/www/frontend
        version: HEAD
      tags: frontend

    - name: List files in /var/www/frontend
      command: ls -la /var/www/frontend
      register: frontend_dir_contents
      tags: frontend

    - name: Print frontend directory contents
      debug:
        var: frontend_dir_contents.stdout_lines
      tags: frontend

    - name: List files in /var/www/frontend/client
      command: ls -la /var/www/frontend/client
      register: client_dir_contents
      tags: frontend

    - name: Print client directory contents
      debug:
        var: client_dir_contents.stdout_lines
      tags: frontend

    - name: Install npm dependencies (frontend)
      command: npm install
      args:
        chdir: /var/www/frontend/client
      tags: frontend

    - name: Build frontend
      command: npm run build
      args:
        chdir: /var/www/frontend/client
      tags: frontend

    - name: Install Node.js (backend)
      apt:
        name: nodejs
        state: present
      tags: backend

    - name: Install npm (backend)
      apt:
        name: npm
        state: present
      tags: backend

    - name: Remove existing backend directory
      file:
        path: /var/www/backend
        state: absent
      tags: backend

    - name: Clone backend repository (full clone)
      git:
        repo: 'https://github.com/OndiekiFrank/yolo.git'
        dest: /var/www/backend
        version: HEAD
      tags: backend

    - name: List files in /var/www/backend
      command: ls -la /var/www/backend
      register: backend_dir_contents
      tags: backend

    - name: Print backend directory contents
      debug:
        var: backend_dir_contents.stdout_lines
      tags: backend

    - name: Install npm dependencies (backend)
      command: npm install
      args:
        chdir: /var/www/backend/backend
      tags: backend

    - name: Start backend server
      command: npm start
      args:
        chdir: /var/www/backend/backend
      tags: backend
