---
- name: Deploy e-commerce application
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Gathering Facts
      ansible.builtin.setup:

    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Download NodeSource setup script
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /tmp/setup_14.x
        mode: '0755'

    - name: Run NodeSource setup script
      ansible.builtin.command:
        cmd: bash /tmp/setup_14.x

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
      tags: nodejs

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present
      tags: npm

  roles:
    - frontend
    - backend
    - database
