---
- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags: nodejs
  become: yes

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: present
  tags: npm
  become: yes

- name: Clone backend repository (full clone)
  ansible.builtin.git:
    repo: 'https://github.com/OndiekiFrank/yolo.git'
    dest: /var/www/backend
    version: HEAD
  tags: backend
  become: yes

- name: Debug: List files in /var/www/backend
  ansible.builtin.command:
    cmd: ls -la /var/www/backend
  register: backend_dir_contents
  tags: backend
  become: yes

- name: Print backend directory contents
  ansible.builtin.debug:
    var: backend_dir_contents.stdout_lines
  tags: backend

- name: Install npm dependencies
  ansible.builtin.command:
    cmd: npm install
    chdir: /var/www/backend
  tags: backend
  become: yes

- name: Start backend server
  ansible.builtin.command:
    cmd: npm start
    chdir: /var/www/backend
  tags: backend
  become: yes
