# roles/backend/tasks/main.yml

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  tags: nodejs

- name: Install npm
  apt:
    name: npm
    state: present
  tags: npm

- name: Clone backend repository
  git:
    repo: "{{ backend_repo }}"
    dest: /var/www/backend
  tags: backend

- name: Install backend dependencies
  npm:
    path: /var/www/backend
    state: present
  tags: backend

- name: Start backend service
  shell: npm start chdir=/var/www/backend
  tags: backend
