---
- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: docker

- name: Clone backend repository
  git:
    repo: "{{ backend_repo }}"
    dest: /home/vagrant/yolo/backend
    version: HEAD
  tags: backend

- name: Build backend Docker image
  command: docker build -t yolo-backend .
  args:
    chdir: /home/vagrant/yolo/backend
  tags: backend

- name: Run backend container
  docker_container:
    name: yolo-backend
    image: yolo-backend
    state: started
    ports:
      - "5000:5000"
  tags: backend
