---
- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags: nodejs
  become: yes

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: present
  tags: npm
  become: yes

- name: Clone frontend repository (full clone)
  ansible.builtin.git:
    repo: 'https://github.com/OndiekiFrank/yolo.git'
    dest: /var/www/frontend
    version: HEAD
  tags: frontend
  become: yes

- name: List files in /var/www/frontend
  ansible.builtin.command:
    cmd: ls -la /var/www/frontend
  register: frontend_dir_contents
  tags: frontend
  become: yes

- name: Print frontend directory contents
  ansible.builtin.debug:
    var: frontend_dir_contents.stdout_lines
  tags: frontend

- name: List files in /var/www/frontend/client
  ansible.builtin.command:
    cmd: ls -la /var/www/frontend/client
  register: client_dir_contents
  tags: frontend
  become: yes

- name: Print client directory contents
  ansible.builtin.debug:
    var: client_dir_contents.stdout_lines
  tags: frontend

- name: Install npm dependencies (frontend)
  ansible.builtin.command:
    cmd: npm install
    chdir: /var/www/frontend/client
  tags: frontend
  become: yes

- name: Build frontend
  ansible.builtin.command:
    cmd: npm run build
    chdir: /var/www/frontend/client
  tags: frontend
  become: yes

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags: nodejs
  become: yes

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: present
  tags: npm
  become: yes

- name: Clone backend repository (full clone)
  ansible.builtin.git:
    repo: 'https://github.com/OndiekiFrank/yolo.git'
    dest: /var/www/backend
    version: HEAD
  tags: backend
  become: yes

- name: List files in /var/www/backend
  ansible.builtin.command:
    cmd: ls -la /var/www/backend
  register: backend_dir_contents
  tags: backend
  become: yes

- name: Print backend directory contents
  ansible.builtin.debug:
    var: backend_dir_contents.stdout_lines
  tags: backend

- name: Install npm dependencies (backend)
  ansible.builtin.command:
    cmd: npm install
    chdir: /var/www/backend/backend
  tags: backend
  become: yes

- name: Start backend server
  ansible.builtin.command:
    cmd: npm start
    chdir: /var/www/backend/backend
  tags: backend
  become: yes
