- name: Install Node.js
  apt:
    name: nodejs
    state: present
  tags: nodejs
  become: yes

- name: Clone frontend repository
  git:
    repo: 'https://github.com/OndiekiFrank/frontend.git'
    dest: /var/www/frontend
  tags: frontend
  become: yes

- name: Build frontend
  command: npm run build
  args:
    chdir: /var/www/frontend
  tags: frontend
  become: yes
