---
- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags: nodejs
  become: yes

- name: Clone frontend repository (shallow clone)
  ansible.builtin.git:
    repo: 'https://github.com/OndiekiFrank/yolo.git'
    dest: /var/www/frontend
    depth: 1
  tags: frontend
  become: yes

- name: Install npm dependencies
  ansible.builtin.command:
    cmd: npm install
    args:
      chdir: /var/www/frontend
  tags: frontend
  become: yes

- name: Build frontend
  ansible.builtin.command:
    cmd: npm run build
    args:
      chdir: /var/www/frontend
  tags: frontend
  become: yes
