- name: Update apt package lists
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gnupg

- name: Add NodeSource repository
  command: curl -sL https://deb.nodesource.com/setup_14.x | bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  tags: nodejs

- name: Clone frontend repository
  git:
    repo: 'https://github.com/yourrepo/frontend.git'
    dest: /var/www/frontend
  tags: frontend

- name: Build frontend
  command: npm run build chdir=/var/www/frontend
  tags: frontend
