---
- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb
    state: present
  tags: database
  become: yes

- name: Ensure MongoDB is running
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: yes
  tags: database
  become: yes
