---
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
  tags: mongodb

- name: Start MongoDB service
  service:
    name: mongodb
    state: started
    enabled: yes
  tags: mongodb

